---
title: "Data processing"
author: "Riesa Cassano"
date: "3/18/2022"
output: html_document
---

```{r libraries, include=FALSE}
library(tidyverse)
library(magrittr)
```

```{r load data, include=FALSE}
# load data
d <- as_tibble(read.csv('data/raw.csv'))

# convert exp_subject_id to a factor
d <- mutate(d, exp_subject_id = as.factor(exp_subject_id))
```

Post-experiment survey data is saved for all subjects who completed it in `survey.csv`. 

```{r process survey data, echo=FALSE}
# get the survey answers and put them in a separate tibble and save
survey_qs <- c('Frequenc','Instr','hour','num_instru','name_instru','age_range',
               'best_instru','music_theory','listen_time','genre1','genre2',
               'genre3','earworm','imagery1','imagery2','imagery3','ab_pitch',
               'relative_pitch','exp_subject_id','familiarity','played_notplayed')

d.survey <- d %>%
  # filter out rows not related to survey
  filter(Block_Name == 'post_survey') %>%
  # only grab survey answers
  select(all_of(survey_qs)) %>%
  # put subject ID at front
  relocate(exp_subject_id) %>%
  print()
  #write_csv('data/survey.csv')
```

```{r processing function for presses, echo=FALSE}
process_responses <- function(data){
  # from the raw version to a list separated by semicolons
  
  # if the subjects didn't respond then the entry will be returned as ""
  data[data==""] <- "values= " 

  all_vals <- data %>%
    strsplit("values=") %>%
    transpose()
  all_vals <- flatten(all_vals[2])
  all_vals <- sub('\"', '', all_vals) # remove \" from the end
  all_vals <- substring(all_vals, 2) # remove first ;
  return(all_vals)
}

process_responses_to_dbls <- function(data){
  # separate values for use as a list of doubles
  processed_data <- c()
  for (i in 1:length(data)){
    vals = flatten(strsplit(toString(data[i][1]), ";"))
    #vals = vals[-1] # remove first value (empty)
    #vals = sub('\"', '', vals) # remove \" from last value
    vals = as.numeric(as.list(vals)) # save as a list of numerics
    vals = as_tibble(vals / 1000) # convert ms to s and make a tibble
    processed_data <- c(processed_data,vals)
  }
  return(processed_data)
}

```


Everything related to the practice task is saved in `practice_task.csv`.

```{r process everything related to practice task, echo=FALSE}
d.practice <- d %>%
  # filter out rows not related to practice task 
  filter(grepl('practice', Task_Name)) %>%
  # we want columns related to practice task
  select(c('exp_subject_id','factor1_tg1_task28',
           'space_press1','space_press2','strategy')) %>%
  # rename practice task column for readability
  rename('practice_task' = 'factor1_tg1_task28')

# text processing of the space presses
space_press1_vals.pr <- process_responses(d.practice$space_press1)
space_press2_vals.pr <- process_responses(d.practice$space_press2)

d.practice <- mutate(d.practice,
                     response1_vals = space_press1_vals.pr,
                     response2_vals = space_press2_vals.pr,
                     space_press1 = NULL,
                     space_press2 = NULL)

d.strat_temp <- d.practice[seq(1, nrow(d.practice), 2),]
d.strat_temp <- select(d.strat_temp, c(exp_subject_id, strategy))
#print(d.strat_temp)

d.other_temp <- d.practice[seq(2, nrow(d.practice), 2),]
d.other_temp <- select(d.other_temp, -strategy)
#print(d.other_temp)

d.practice_filtered <- d.other_temp
d.practice_filtered$strategy <- d.strat_temp$strategy
#write_csv(d.practice_filtered, 'data/practice_task.csv')
print(d.practice_filtered)
```

Responses for the actual task are processed similarly. Responses and strategy answers are extracted together from the raw file and then separated. Strategy answers are saved in `strategy.csv`

```{r get all rows for actual task, echo=FALSE}
d.responses_all <- d %>%
  # keep only rows for main task (this includes response task and strategy)
  filter(grepl('block_', Block_Name)) %>%
  # keep relevant columns
  select(c('exp_subject_id','Task_Name',
           'space_press1','space_press2','strategy')) #%>%
  #print()

d.strategy <- d.responses_all %>%
  # strategy questions are labeled with 25%, 50%, 75%, or 100%
  # matching the subject's progress through the experiment
  filter(grepl('%', Task_Name)) %>%
  # drop the (now empty) response columns
  select(c(-space_press1, -space_press2)) %>%
  write_csv('data/strategy.csv')
  #print()

```